bbox_padding: 0.2
checkpoint: ./best_model.pth
config: ./configs/config_jetson.yaml
data_root: ./data/UAV-Anti-UAV/Test
max_anchor_size: 5
max_recent_size: 15
num_frames: 16
num_imposters: 15
output_video: ./output_robustness.mp4
seq_dir: ./data/UAV-Anti-UAV/Test/UAV-Anti-UAV_Test_000330
threshold: 0.75
